### ISSUE TITLE
是直接把文件扔到网站根目录吗？

### ISSUE THREAD

**Issue by acgbox233** [sym233/core-values-encoder#12]
我这样做了之后，能够打开页面但点击加密解密按钮没有反应。求正确使用方法！

**Comment by yatyricky** [comment]
试试这个？
https://github.com/yatyricky/core-values-encoder-crx

**Comment by sym233** [comment]
master分支是没编译过的，你可以用gh-page分支的

**Comment by 1a57danc3** [comment]
```npm run build```
