### ISSUE TITLE
再别康桥

### ISSUE THREAD

**Issue by zghne** [sym233/core-values-encoder#16]
诚信自由平等爱国公正爱国友善法治友善爱国平等爱国爱国诚信富强友善平等友善爱国平等诚信民主诚信富强友善平等法治诚信自由公正诚信富强民主友善自由平等文明富强诚信自由平等友善平等友善爱国敬业富强诚信自由平等诚信民主诚信平等敬业法治友善爱国公正敬业民主友善自由敬业富强友善自由诚信自由爱国诚信民主友善法治诚信民主友善平等诚信自由爱国友善平等诚信和谐诚信民主诚信民主友善爱国法治敬业诚信富强爱国自由诚信自由公正爱国爱国敬业民主友善爱国爱国友善平等平等诚信民主富强诚信自由自由诚信民主友善自由爱国公正友善爱国诚信平等诚信民主诚信文明爱国诚信文明富强诚信富强诚信自由公正友善自由诚信和谐诚信富强和谐诚信自由平等诚信富强公正爱国文明友善爱国公正爱国爱国敬业民主诚信自由爱国友善平等友善法治诚信民主友善平等友善爱国爱国友善平等诚信和谐友善平等诚信民主友善爱国法治敬业友善自由爱国自由友善爱国公正敬业友善法治诚信富强平等友善爱国友善敬业友善平等诚信文明敬业诚信民主富强友善自由友善爱国公正爱国爱国敬业民主诚信自由爱国友善平等诚信和谐友善平等友善平等诚信自由爱国诚信民主友善法治诚信民主友善平等诚信自由法治敬业诚信富强爱国自由友善爱国公正爱国诚信民主敬业诚信民主诚信自由公正爱国敬业爱国友善平等友善爱国友善敬业友善平等友善公正爱国友善公正富强诚信富强友善爱国自由友善平等友善法治敬业友善公正友善爱国平等爱国爱国友善自由诚信民主友善爱国爱国诚信富强平等友善平等诚信平等友善爱国平等友善自由自由诚信富强敬业友善爱国法治敬业诚信富强爱国自由诚信自由自由诚信民主友善自由敬业民主诚信自由平等友善平等友善法治友善自由敬业诚信自由和谐爱国富强爱国文明富强诚信富强诚信自由敬业爱国文明友善自由和谐诚信自由公正友善平等文明诚信民主和谐诚信自由法治敬业平等敬业自由诚信自由法治敬业友善自由爱国自由诚信自由敬业爱国法治敬业民主诚信自由公正敬业诚信平等诚信民主和谐友善爱国诚信平等友善平等诚信文明爱国友善公正富强诚信富强友善爱国公正敬业爱国友善自由友善敬业诚信自由平等友善自由自由敬业平等友善爱国敬业敬业爱国友善平等和谐友善爱国自由友善平等爱国诚信富强友善法治诚信自由法治敬业友善自由爱国自由诚信自由公正敬业公正诚信民主富强诚信自由平等友善自由爱国敬业爱国友善爱国友善敬业诚信民主友善公正敬业友善平等富强友善自由友善爱国公正友善平等和谐友善自由文明诚信自由平等爱国平等爱国敬业诚信自由敬业爱国法治爱国诚信文明诚信自由法治敬业友善自由爱国自由诚信自由爱国爱国敬业友善平等和谐友善爱国平等诚信民主友善法治诚信民主民主友善爱国诚信平等诚信民主诚信文明爱国诚信文明富强诚信富强友善爱国平等敬业友善公正友善自由爱国诚信自由公正爱国爱国敬业民主诚信自由法治敬业诚信富强爱国自由诚信自由平等友善平等诚信平等爱国和谐诚信自由平等友善自由自由诚信民主自由诚信自由爱国爱国友善法治友善自由民主诚信自由公正友善平等友善公正友善平等诚信自由友善爱国和谐爱国富强爱国文明富强友善自由友善爱国爱国友善平等友善法治诚信富强友善敬业友善爱国公正友善平等和谐诚信富强平等友善爱国自由友善平等爱国爱国诚信富强友善爱国法治敬业诚信富强爱国自由友善爱国敬业敬业诚信和谐敬业文明友善爱国爱国爱国友善法治爱国法治友善爱国友善敬业诚信民主诚信文明爱国诚信文明富强诚信富强友善爱国公正诚信民主文明诚信民主敬业友善爱国公正诚信民主文明诚信民主敬业诚信自由法治敬业诚信富强爱国自由诚信自由平等敬业友善公正友善自由爱国友善爱国公正诚信民主富强友善平等自由友善爱国平等友善平等诚信富强敬业平等诚信自由公正爱国友善平等敬业友善平等诚信自由公正敬业民主爱国法治友善爱国友善敬业友善平等友善公正敬业友善平等富强友善自由诚信自由平等敬业友善公正诚信富强爱国友善爱国平等友善平等诚信富强友善平等法治诚信自由公正友善平等文明诚信民主和谐诚信自由法治敬业友善自由爱国自由友善爱国公正敬业诚信平等敬业自由友善爱国公正友善平等和谐友善自由文明友善爱国敬业爱国法治爱国友善公正诚信自由友善敬业友善平等友善公正爱国诚信文明富强诚信富强诚信自由公正爱国爱国敬业民主诚信自由法治敬业自由敬业爱国诚信自由平等诚信民主友善敬业爱国和谐友善爱国平等爱国民主敬业友善自由诚信自由自由友善平等爱国爱国富强友善爱国公正敬业诚信和谐诚信富强民主诚信自由公正诚信民主富强友善平等自由诚信自由爱国爱国友善法治爱国敬业友善爱国诚信平等友善平等友善公正爱国民主富强诚信富强友善爱国敬业爱国文明诚信富强和谐诚信自由公正友善自由公正爱国公正诚信自由爱国爱国友善法治诚信富强诚信民主诚信自由自由友善平等爱国爱国诚信民主友善爱国法治敬业友善自由爱国自由友善爱国自由诚信民主爱国爱国富强诚信自由公正友善平等友善法治诚信富强友善法治诚信自由诚信平等诚信民主诚信文明爱国友善公正富强友善自由友善爱国自由诚信民主爱国爱国诚信和谐诚信自由公正敬业爱国友善自由诚信平等友善爱国公正诚信民主爱国爱国平等友善爱国公正诚信民主和谐爱国敬业诚信自由诚信平等友善平等友善公正爱国友善公正富强诚信富强友善爱国公正敬业爱国友善自由友善敬业诚信自由平等友善自由自由友善自由敬业友善爱国自由友善平等爱国爱国诚信富强诚信自由爱国敬业敬业友善平等敬业诚信自由诚信平等友善平等诚信文明敬业诚信民主富强诚信富强友善爱国公正爱国诚信平等爱国敬业友善爱国法治诚信富强文明爱国诚信自由诚信自由平等敬业友善公正友善自由爱国友善爱国公正诚信民主平等友善自由诚信自由诚信自由爱国敬业法治友善平等友善平等友善爱国敬业敬业法治友善平等自由友善爱国诚信平等友善平等诚信文明爱国友善公正富强友善自由诚信自由公正友善平等文明爱国敬业诚信自由公正友善平等法治爱国富强诚信自由法治敬业友善法治爱国富强友善爱国平等诚信民主诚信和谐诚信富强敬业友善爱国爱国敬业敬业友善平等敬业诚信自由自由友善平等诚信文明友善平等诚信文明友善爱国法治敬业友善自由爱国自由友善爱国公正诚信富强文明诚信富强公正诚信自由和谐爱国富强爱国文明富强友善自由诚信自由平等诚信富强友善敬业诚信民主友善平等诚信自由公正诚信富强文明友善自由公正诚信自由友善敬业诚信民主诚信文明敬业诚信平等富强友善自由诚信自由公正敬业文明敬业民主友善爱国自由友善平等爱国爱国富强友善爱国公正敬业自由友善自由友善敬业诚信自由敬业敬业平等诚信民主诚信平等诚信自由法治诚信富强诚信平等敬业敬业友善爱国友善敬业友善平等友善公正爱国友善公正富强友善自由友善爱国平等敬业富强敬业民主诚信自由敬业敬业友善法治敬业文明友善爱国爱国爱国友善法治爱国敬业诚信自由公正敬业友善平等诚信民主自由友善爱国敬业敬业诚信和谐敬业文明诚信自由平等诚信富强自由爱国自由友善爱国公正友善平等友善公正友善自由友善平等友善爱国公正诚信民主友善自由诚信富强友善敬业友善爱国诚信平等诚信民主诚信文明敬业友善平等富强诚信富强友善爱国公正诚信民主友善平等诚信富强民主友善爱国爱国友善平等诚信和谐诚信民主友善法治友善爱国自由诚信民主爱国爱国富强友善爱国爱国爱国爱国诚信民主敬业友善爱国公正敬业爱国敬业友善敬业友善爱国爱国诚信民主友善爱国爱国敬业友善爱国诚信平等友善平等诚信文明爱国友善公正富强友善自由友善爱国平等敬业友善公正友善自由爱国友善爱国公正敬业爱国敬业友善敬业诚信自由爱国友善平等友善爱国爱国敬业诚信自由公正敬业公正敬业民主友善爱国公正敬业公正敬业和谐诚信自由敬业爱国法治爱国友善公正友善爱国公正敬业自由友善平等诚信自由诚信自由公正诚信富强友善法治爱国诚信文明友善爱国和谐爱国富强爱国文明富强诚信富强诚信自由自由友善平等友善法治爱国公正友善爱国公正爱国爱国敬业民主诚信自由自由诚信民主爱国爱国友善法治诚信自由爱国爱国和谐友善平等友善法治诚信自由公正敬业自由诚信民主友善爱国诚信自由公正友善自由诚信和谐爱国友善公正诚信自由诚信平等友善平等诚信文明爱国友善公正富强诚信富强友善爱国公正爱国文明爱国自由诚信自由公正爱国文明爱国自由友善爱国公正敬业爱国诚信富强友善敬业友善爱国平等爱国爱国诚信富强友善平等诚信自由法治友善自由公正友善平等诚信民主友善爱国法治敬业诚信富强爱国自由友善爱国法治友善自由友善公正敬业敬业友善爱国法治友善自由友善爱国友善自由友善平等诚信自由诚信平等友善平等友善公正敬业友善平等富强诚信富强友善爱国平等友善自由自由爱国友善敬业诚信自由爱国敬业敬业诚信富强诚信民主友善爱国自由诚信民主敬业敬业诚信平等诚信自由自由友善平等爱国友善平等诚信富强诚信自由公正爱国爱国敬业民主友善爱国公正友善平等文明爱国敬业诚信自由敬业友善平等友善平等敬业爱国友善爱国诚信平等诚信民主友善公正爱国友善公正富强诚信富强诚信自由公正友善平等文明爱国敬业友善爱国敬业友善平等诚信民主敬业爱国友善爱国公正敬业爱国诚信富强友善敬业诚信自由自由友善平等诚信民主爱国友善自由诚信自由公正敬业敬业敬业友善自由诚信自由法治敬业友善自由爱国自由诚信自由平等友善平等友善自由诚信民主法治友善爱国公正友善自由民主诚信富强平等诚信自由诚信平等诚信民主诚信文明爱国民主富强诚信富强友善爱国公正爱国文明爱国自由诚信自由公正爱国文明爱国自由诚信自由法治敬业诚信富强爱国自由诚信自由公正爱国爱国敬业民主友善爱国爱国诚信民主平等友善平等富强友善爱国自由诚信民主友善自由爱国公正友善爱国诚信平等诚信民主诚信文明爱国友善公正富强友善自由友善爱国公正诚信富强诚信和谐友善自由和谐友善爱国平等诚信富强公正爱国文明友善爱国公正爱国爱国敬业民主诚信自由公正爱国文明爱国自由友善爱国公正爱国文明爱国自由友善爱国法治敬业友善自由爱国自由友善爱国公正敬业诚信和谐友善自由平等友善爱国友善敬业诚信民主友善公正敬业诚信民主富强友善自由友善爱国公正爱国爱国敬业民主诚信自由公正爱国友善公正诚信富强平等诚信自由自由诚信民主爱国爱国富强友善爱国公正爱国诚信文明诚信富强平等诚信自由爱国诚信富强民主诚信富强和谐友善爱国爱国诚信富强文明敬业公正友善爱国诚信平等友善平等诚信文明爱国诚信文明富强友善自由诚信自由自由友善平等爱国爱国诚信和谐诚信自由平等诚信民主爱国友善自由公正友善爱国爱国诚信民主平等友善平等富强友善爱国自由友善平等爱国爱国富强诚信自由法治爱国敬业爱国法治诚信自由自由友善平等友善自由敬业民主友善爱国平等友善平等诚信和谐诚信富强敬业诚信自由和谐爱国富强爱国文明

**Comment by kouhe3** [comment]
草
