### ISSUE TITLE
求制作基于base64的编码器

### ISSUE THREAD

**Issue by kouhe3** [sym233/core-values-encoder#18]
base12明显太长了....更何况这个还是两个字的。
求制作一个基于base64的千字文编码器

**Comment by sym233** [comment]
没啥意义，千字文和本项目也没什么关联

**Comment by kouhe3** [comment]
> 没啥意义，千字文和本项目也没什么关联
@sym233 
汉字加密为汉字的base64编码器，应该很有意思吧

**Comment by sym233** [comment]
与佛论禅

**Comment by kouhe3** [comment]
> 与佛论禅
@sym233 
多谢指路
