### ISSUE TITLE
Support for emoji

### ISSUE THREAD

**Issue by sorz** [sym233/core-values-encoder#3]
`str2utf8()` does not work on strings that contain emoji (or any others
beyond the Basic Multilingual Plane).

By a quick search, `TextEncoder` and `TextDecoder` may be a good alternative,
but they seems not be supported by browser well. 🤔

**Comment by sorz** [comment]
It would be great if we can use it to make some bad emoji (like 🇹🇼) 和谐 again. (

**Comment by sym233** [comment]
It seems that `encodeURIComponent`  doesn't support emoji. I have never concern about that.

**Comment by sorz** [comment]
Emm, some experiments:
```javascript
>> encodeURIComponent('🌚')
<- "%F0%9F%8C%9A"

>> '🌚'.length
<- 2

>> encodeURIComponent('🌚'[0])
!! URIError: malformed URI sequence
``` 
I guess the problem is that `Array.prototype.map` split the single character into two,
then `encodeURIComponent()` complained since it got only half of things.

**Comment by sym233** [comment]
Done.
