### ISSUE TITLE
好复杂啊，看看我的

### ISSUE THREAD

**Issue by ghost** [sym233/core-values-encoder#5]
https://hl4a.cn/core-values-js/
不过我是强行翻译了😂

**Comment by duhd1993** [comment]
@MikaGuraN 这，这是什么黑科技编程语言？

**Comment by sym233** [comment]
易js233
看起来好费劲啊，还不缩进

**Comment by ghost** [comment]
@lonelykid 加了中文关键字的js😂 不是什么黑科技语言

**Comment by ghost** [comment]
@sym233 😂风评被害 ，没缩进是因为写的时候比较急，又没有格式化的工具，就成了这样

**Comment by sym233** [comment]
代码是手打的还是生成的，不会有切输入法烦躁吗

**Comment by ghost** [comment]
@sym233  手打的。不过手机上只要一点就切换了，很方便。

**Comment by penguin806** [comment]
no manual, no documentation for HL4A, can't understand your code.
